services:
  - type: web
    name: votre-projet-astro
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: NODE_ENV
        value: production
    regions:
      - oregon